#!/usr/bin/env ruby

=begin

  Copyright (c) 2014, Cosmin Gorgovan
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer. 
  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=end

unless ARGV[0]
  puts "lpc_part_ids automatically extracts part IDs from NXP user manuals for LPC\nmicrocontrollers that have previously been converted to text format using pdftotext.\n\n"
  puts "\tUsage: lpc_part_ids [FILENAME]\n\n" 
  abort
end

part_ids = {}
part_names = {}

file = File.open(ARGV[0], :encoding => "UTF-8")
res = file.read.scan(/(?<part>LPC\d\d\w?\d\dH?)(F\w{2}\d{2})?(\/(?<variant>\d{2,3}))?(\[\d\])?( = |\n\n(\d+\n\n)?)(?<ids>0x[\dxA-F \/]+)/)

res.each do |r|
  part = r[0]
  variant = r[1]
  device_name = part.to_s
  device_name += '_' + variant.to_s if variant

  ids = r[2].gsub(' ', '').split('/')
  ids.each do |id|
    unless part_ids[id]
      if part_names[device_name]
        part_names[device_name] += 1
      else
         part_names[device_name] = 1
      end
      puts "#define #{device_name}_#{part_names[device_name].to_s} #{id}"
      part_ids[id] = true
    end

  end
end

